server {
  listen 80;
  server_name gitlabreport.forvestlab.ir;

  root /var/www/gitlabreport/dist;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /env.js {
    alias /var/www/gitlabreport/dist/env.js;
    add_header Cache-Control "no-store";
  }

  location /api/ {
    proxy_pass http://127.0.0.1:3001/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 300;
  }

  location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico)$ {
    try_files $uri =404;
    expires 7d;
    access_log off;
  }
}
